services:
    freqtrade:
        # image: freqtradeorg/freqtrade:stable
        image: freqtradeorg/freqtrade:stable_freqairl
        restart: unless-stopped
        container_name: ft
        volumes:
            - ./core/user_data:/freqtrade/user_data
        ports:
            - "127.0.0.1:8080:8080"
        command: >
            trade
            --logfile /freqtrade/user_data/logs/freqtrade.log
            --db-url sqlite:////freqtrade/user_data/tradesv3.sqlite
            --config /freqtrade/user_data/config.json
            --freqaimodel XGBoostRegressor
            --strategy FreqaiExampleStrategy
